### PR TITLE
[feat] online store 2.0 structure

### PR DESCRIPTION
**Pull request by leeuwis**
- [x] Changed all template files from `liquid` to `json` files
- [x] Added login page for stores without [Multipass](https://shopify.dev/api/multipass) (Shopify Plus feature)
- [x] Added giftcard template since it's not supported via the Storefront API
- [x] Update `read.md` file with the 2 new features above

_Note: Main structure incl. login and gift card templates is based on [dawn](https://github.com/Shopify/dawn)_

### CODE REVIEW

**Comment by leeuwis** [comment]
closes #3

**Review by BJvdA — APPROVED** [review]
LGTM 👍

**Comment by MaSchVam** [comment]
Hey @leeuwis ,

Thanks for your notification - looks good, I'll give this a go!

**Comment by leeuwis** [comment]
Closes #2

**Pull request merged**
